name: "Todo"

on: ["push"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: alstr/todo-to-issue-action@v4.6.2
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_MARKER: "//"
          LABEL: "// TODO"
